#!/usr/bin/with-contenv bash
#shellcheck shell=bash

cd "$PATH_OVERPUTNEY" || exit 1

# shellcheck disable=SC2016
python3 ./tracker.py \
  2>&1 | stdbuf -o0 awk '{print "[overputney] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 10
