#!/usr/bin/with-contenv bash
# shellcheck shell=bash

YELLOW='\033[1;33m'
NOCOLOR='\033[0m'
echo -ne "${YELLOW}"

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi

echo -ne "${NOCOLOR}"
